#NDK_TOOLCHAIN_VERSION := 4.9
APP_STL := c++_static
APP_ABI := arm64-v8a armeabi-v7a 
#APP_ABI := armeabi-v7a
APP_PLATFORM := android-21
APP_MODULES := sbmobile
APP_OPTIM := release
#APP_CPPFLAGS := -O3 -std=c++11 -fexceptions -frtti -DBOOST_NO_CXX11_SCOPED_ENUMS -DSB_NO_ASSIMP
APP_CPPFLAGS := -O3 -std=c++11 -fexceptions -fpermissive -frtti -DBOOST_NO_CXX11_SCOPED_ENUMS -DBOOST_RESULT_OF_USE_DECLTYPE -DNDEBUG -DSB_NO_ASSIMP -DSB_NO_ODE_PHYSICS -DSB_NO_VHMSG -DSB_NO_BONEBUS
#APP_CPPFLAGS := -O0 -g -std=c++11 -fexceptions -frtti -DBOOST_NO_CXX11_SCOPED_ENUMS -DBOOST_RESULT_OF_USE_DECLTYPE

APP_SHORT_COMMANDS := true
