# Autogenerated by SmartBody
# -------------------- lights
print "Save Lights"

# ---- light: light0
obj = scene.getPawn("light0")
if obj == None:
	obj = scene.createPawn("light0")
obj.setPosition(SrVec(0, 1, 0))
obj.setOrientation(SrQuat(0.662327, -0.247634, -0.247634, 0.662327))
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",0.8, 0.75, 0.7)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  0.8, 0.75, 0.7, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0.8, 0.75, 0.7)
	attr.setValue(vec1)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",1)
else:
	attr = obj.createDoubleAttribute("posY", 1, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(1)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",-41)
else:
	attr = obj.createDoubleAttribute("rotY", -41, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(-41)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",90)
else:
	attr = obj.createDoubleAttribute("rotZ", 90, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(90)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)

# ---- light: light1
obj = scene.getPawn("light1")
if obj == None:
	obj = scene.createPawn("light1")
obj.setPosition(SrVec(0, 1, 0))
obj.setOrientation(SrQuat(0.0984102, -0.700225, -0.700225, 0.0984102))
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enabled") != None :
	obj.setBoolAttribute("enabled",True)
else:
	attr = obj.createBoolAttribute("enabled", True, True, "LightParameters", 200, False, False, False, "Is the light enabled?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",1, 1, 1)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  1, 1, 1, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",1)
else:
	attr = obj.createDoubleAttribute("posY", 1, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(1)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",196)
else:
	attr = obj.createDoubleAttribute("rotY", 196, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(196)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",90)
else:
	attr = obj.createDoubleAttribute("rotZ", 90, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(90)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)

# ---- light: light2
obj = scene.getPawn("light2")
if obj == None:
	obj = scene.createPawn("light2")
obj.setPosition(SrVec(0, 1, 0))
obj.setOrientation(SrQuat(0.67037, 0.224953, 0.224953, 0.67037))
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enabled") != None :
	obj.setBoolAttribute("enabled",True)
else:
	attr = obj.createBoolAttribute("enabled", True, True, "LightParameters", 200, False, False, False, "Is the light enabled?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",1, 1, 1)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  1, 1, 1, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",1)
else:
	attr = obj.createDoubleAttribute("posY", 1, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(1)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",217.1)
else:
	attr = obj.createDoubleAttribute("rotY", 217.1, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(217.1)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",90)
else:
	attr = obj.createDoubleAttribute("rotZ", 90, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(90)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)

# ---- light: light3
obj = scene.getPawn("light3")
if obj == None:
	obj = scene.createPawn("light3")
obj.setPosition(SrVec(0, 0, 0))
obj.setOrientation(SrQuat(0.999962, 5.70368e-019, 6.53577e-017, 0.00872654))
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enabled") != None :
	obj.setBoolAttribute("enabled",False)
else:
	attr = obj.createBoolAttribute("enabled", True, True, "LightParameters", 200, False, False, False, "Is the light enabled?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  0, 0, 0, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",1)
else:
	attr = obj.createDoubleAttribute("rotZ", 1, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(1)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)
