LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := ode
MY_DIR := ../odeSrc/
LOCAL_CFLAGS    := -DBUILD_ANDROID
LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(MY_DIR)/include $(LOCAL_PATH)/$(MY_DIR)/OPCODE
LOCAL_SRC_FILES := $(MY_DIR)/ode/src/array.cpp	\
					$(MY_DIR)/ode/src/box.cpp \
					$(MY_DIR)/ode/src/capsule.cpp \
					$(MY_DIR)/ode/src/collision_cylinder_box.cpp \
					$(MY_DIR)/ode/src/collision_cylinder_plane.cpp \
					$(MY_DIR)/ode/src/collision_cylinder_sphere.cpp \
					$(MY_DIR)/ode/src/collision_cylinder_trimesh.cpp \
					$(MY_DIR)/ode/src/collision_kernel.cpp \
					$(MY_DIR)/ode/src/collision_quadtreespace.cpp \
					$(MY_DIR)/ode/src/collision_sapspace.cpp \
					$(MY_DIR)/ode/src/collision_space.cpp \
					$(MY_DIR)/ode/src/collision_transform.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_box.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_ccylinder.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_disabled.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_distance.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_gimpact.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_opcode.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_plane.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_ray.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_sphere.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_trimesh.cpp \
					$(MY_DIR)/ode/src/collision_trimesh_trimesh_new.cpp \
					$(MY_DIR)/ode/src/collision_util.cpp \
					$(MY_DIR)/ode/src/convex.cpp \
					$(MY_DIR)/ode/src/cylinder.cpp \
					$(MY_DIR)/ode/src/error.cpp \
					$(MY_DIR)/ode/src/export-dif.cpp \
					$(MY_DIR)/ode/src/fastdot.c \
					$(MY_DIR)/ode/src/fastldlt.c \
					$(MY_DIR)/ode/src/fastlsolve.c \
					$(MY_DIR)/ode/src/fastltsolve.c \
					$(MY_DIR)/ode/src/heightfield.cpp \
					$(MY_DIR)/ode/src/lcp.cpp \
					$(MY_DIR)/ode/src/mass.cpp \
					$(MY_DIR)/ode/src/mat.cpp \
					$(MY_DIR)/ode/src/matrix.cpp \
					$(MY_DIR)/ode/src/memory.cpp \
					$(MY_DIR)/ode/src/misc.cpp \
					$(MY_DIR)/ode/src/obstack.cpp \
					$(MY_DIR)/ode/src/ode.cpp \
					$(MY_DIR)/ode/src/odeinit.cpp \
					$(MY_DIR)/ode/src/odemath.cpp \
					$(MY_DIR)/ode/src/odeou.cpp \
					$(MY_DIR)/ode/src/odetls.cpp \
					$(MY_DIR)/ode/src/plane.cpp \
					$(MY_DIR)/ode/src/quickstep.cpp \
					$(MY_DIR)/ode/src/ray.cpp \
					$(MY_DIR)/ode/src/rotation.cpp \
					$(MY_DIR)/ode/src/sphere.cpp \
					$(MY_DIR)/ode/src/step.cpp \
					$(MY_DIR)/ode/src/stepfast.cpp \
					$(MY_DIR)/ode/src/testing.cpp \
					$(MY_DIR)/ode/src/timer.cpp \
					$(MY_DIR)/ode/src/util.cpp \
					$(MY_DIR)/ode/src/joints/amotor.cpp \
					$(MY_DIR)/ode/src/joints/ball.cpp \
					$(MY_DIR)/ode/src/joints/contact.cpp \
					$(MY_DIR)/ode/src/joints/fixed.cpp \
					$(MY_DIR)/ode/src/joints/hinge.cpp \
					$(MY_DIR)/ode/src/joints/hinge2.cpp \
					$(MY_DIR)/ode/src/joints/joint.cpp \
					$(MY_DIR)/ode/src/joints/lmotor.cpp \
					$(MY_DIR)/ode/src/joints/null.cpp \
					$(MY_DIR)/ode/src/joints/piston.cpp \
					$(MY_DIR)/ode/src/joints/plane2d.cpp \
					$(MY_DIR)/ode/src/joints/pr.cpp \
					$(MY_DIR)/ode/src/joints/pu.cpp \
					$(MY_DIR)/ode/src/joints/slider.cpp \
					$(MY_DIR)/ode/src/joints/universal.cpp \
					$(MY_DIR)/OPCODE/Opcode.cpp \
					$(MY_DIR)/OPCODE/OPC_AABBCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_AABBTree.cpp \
					$(MY_DIR)/OPCODE/OPC_BaseModel.cpp \
					$(MY_DIR)/OPCODE/OPC_Collider.cpp \
					$(MY_DIR)/OPCODE/OPC_Common.cpp \
					$(MY_DIR)/OPCODE/OPC_HybridModel.cpp \
					$(MY_DIR)/OPCODE/OPC_LSSCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_MeshInterface.cpp \
					$(MY_DIR)/OPCODE/OPC_Model.cpp \
					$(MY_DIR)/OPCODE/OPC_OBBCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_OptimizedTree.cpp \
					$(MY_DIR)/OPCODE/OPC_Picking.cpp \
					$(MY_DIR)/OPCODE/OPC_PlanesCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_RayCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_SphereCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_TreeBuilders.cpp \
					$(MY_DIR)/OPCODE/OPC_TreeCollider.cpp \
					$(MY_DIR)/OPCODE/OPC_VolumeCollider.cpp \
					$(MY_DIR)/OPCODE/Ice/IceAABB.cpp \
					$(MY_DIR)/OPCODE/Ice/IceContainer.cpp \
					$(MY_DIR)/OPCODE/Ice/IceHPoint.cpp \
					$(MY_DIR)/OPCODE/Ice/IceIndexedTriangle.cpp \
					$(MY_DIR)/OPCODE/Ice/IceMatrix3x3.cpp \
					$(MY_DIR)/OPCODE/Ice/IceMatrix4x4.cpp \
					$(MY_DIR)/OPCODE/Ice/IceOBB.cpp \
					$(MY_DIR)/OPCODE/Ice/IcePlane.cpp \
					$(MY_DIR)/OPCODE/Ice/IcePoint.cpp \
					$(MY_DIR)/OPCODE/Ice/IceRandom.cpp \
					$(MY_DIR)/OPCODE/Ice/IceRay.cpp \
					$(MY_DIR)/OPCODE/Ice/IceRevisitedRadix.cpp \
					$(MY_DIR)/OPCODE/Ice/IceSegment.cpp \
					$(MY_DIR)/OPCODE/Ice/IceTriangle.cpp \
					$(MY_DIR)/OPCODE/Ice/IceUtils.cpp
include $(BUILD_STATIC_LIBRARY)
