# Autogenerated by SmartBody
# -------------------- lights
print "Save Lights"

# ---- light: light0
obj = scene.getPawn("light0")
if obj == None:
	obj = scene.createPawn("light0")
obj.setPosition(SrVec(-0.24, 1.71, 0))
obj.setOrientation(SrQuat(0.441373, -0.256798, 0.16341, 0.844122))
if obj.getAttribute("blendTexturesWithLighting") != None :
	obj.setBoolAttribute("blendTexturesWithLighting",True)
else:
	attr = obj.createBoolAttribute("blendTexturesWithLighting", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("collisionShape") != None :
	obj.setStringAttribute("collisionShape","null")
else:
	attr = obj.createStringAttribute("collisionShape",  "null", True, "Physics", 350, False, False, False, "Initializes the pawn as a physics object.")
	attr.setDefaultValue("null")
	attr.setValue("null")
	validValues = StringVec()
	validValues.append("null")
	validValues.append("sphere")
	validValues.append("box")
	validValues.append("capsule")
	attr.setValidValues(validValues)
if obj.getAttribute("collisionShapeScale") != None :
	obj.setVec3Attribute("collisionShapeScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("collisionShapeScale",  1, 1, 1, True, "Physics", 360, False, False, False, "Scaling of physics-based shape.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("color") != None :
	obj.setVec3Attribute("color",1, 0, 0)
else:
	attr = obj.createVec3Attribute("color",  1, 0, 0, True, "Display", 6, False, False, False, "Object color.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enablePhysics") != None :
	obj.setBoolAttribute("enablePhysics",False)
else:
	attr = obj.createBoolAttribute("enablePhysics", False, True, "Physics", 310, False, False, False, "Enables or disables physics for this pawn.")
	attr.setDefaultValue(False)
	attr.setValue(False)
if obj.getAttribute("enabled") != None :
	obj.setBoolAttribute("enabled",True)
else:
	attr = obj.createBoolAttribute("enabled", True, True, "LightParameters", 200, False, False, False, "Is the light enabled?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightAmbientColor") != None :
	obj.setVec3Attribute("lightAmbientColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightAmbientColor",  0, 0, 0, True, "LightParameters", 220, False, False, False, " Ambient light color")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("lightCastShadow") != None :
	obj.setBoolAttribute("lightCastShadow",True)
else:
	attr = obj.createBoolAttribute("lightCastShadow", True, True, "LightParameters", 300, False, False, False, "Does the light cast shadow?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightConstantAttenuation") != None :
	obj.setDoubleAttribute("lightConstantAttenuation",1)
else:
	attr = obj.createDoubleAttribute("lightConstantAttenuation", 1, True, "LightParameters", 270, False, False, False, "Constant attenuation")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",1, 0.95, 0.8)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  1, 0.95, 0.8, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 0.95, 0.8)
	attr.setValue(vec1)
if obj.getAttribute("lightIsDirectional") != None :
	obj.setBoolAttribute("lightIsDirectional",True)
else:
	attr = obj.createBoolAttribute("lightIsDirectional", True, True, "LightParameters", 205, False, False, False, "Is the light directional?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightLinearAttenuation") != None :
	obj.setDoubleAttribute("lightLinearAttenuation",1)
else:
	attr = obj.createDoubleAttribute("lightLinearAttenuation", 1, True, "LightParameters", 280, False, False, False, " Linear attenuation.")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("lightQuadraticAttenuation") != None :
	obj.setDoubleAttribute("lightQuadraticAttenuation",0)
else:
	attr = obj.createDoubleAttribute("lightQuadraticAttenuation", 0, True, "LightParameters", 290, False, False, False, "Quadratic attenuation")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("lightShadowMapSize") != None :
	obj.setIntAttribute("lightShadowMapSize",1024)
else:
	attr = obj.createIntAttribute("lightShadowMapSize", 1024, True, "LightParameters", 310, False, False, False, "Size of the shadow map")
	attr.setDefaultValue(1024)
	attr.setValue(1024)
if obj.getAttribute("lightSpecularColor") != None :
	obj.setVec3Attribute("lightSpecularColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightSpecularColor",  0, 0, 0, True, "LightParameters", 230, False, False, False, "Specular light color")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("lightSpotCutoff") != None :
	obj.setDoubleAttribute("lightSpotCutoff",180)
else:
	attr = obj.createDoubleAttribute("lightSpotCutoff", 180, True, "LightParameters", 260, False, False, False, "Spotlight cutoff angle")
	attr.setDefaultValue(180)
	attr.setValue(180)
if obj.getAttribute("lightSpotDirection") != None :
	obj.setVec3Attribute("lightSpotDirection",0, 0, -1)
else:
	attr = obj.createVec3Attribute("lightSpotDirection",  0, 0, -1, True, "LightParameters", 250, False, False, False, "Spotlight direction")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, -1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, -1)
	attr.setValue(vec1)
if obj.getAttribute("lightSpotExponent") != None :
	obj.setDoubleAttribute("lightSpotExponent",0)
else:
	attr = obj.createDoubleAttribute("lightSpotExponent", 0, True, "LightParameters", 240, False, False, False, " Spotlight exponent.")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("mesh") != None :
	obj.setStringAttribute("mesh","")
else:
	attr = obj.createStringAttribute("mesh",  "", True, "Display", 400, False, False, False, "Geometry/mesh")
	attr.setDefaultValue("")
	attr.setValue("")
	validValues = StringVec()
	attr.setValidValues(validValues)
if obj.getAttribute("meshPivot") != None :
	obj.setVec3Attribute("meshPivot",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshPivot",  0, 0, 0, True, "Display", 440, False, False, False, "Mesh pivot offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshRotation") != None :
	obj.setVec3Attribute("meshRotation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshRotation",  0, 0, 0, True, "Display", 430, False, False, False, "Mesh rotation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshScale") != None :
	obj.setVec3Attribute("meshScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("meshScale",  1, 1, 1, True, "Display", 410, False, False, False, "Scale of geometry/mesh")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("meshTranslation") != None :
	obj.setVec3Attribute("meshTranslation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshTranslation",  0, 0, 0, True, "Display", 420, False, False, False, "Mesh translation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("posX") != None :
	obj.setDoubleAttribute("posX",-0.24)
else:
	attr = obj.createDoubleAttribute("posX", -0.24, True, "transform", 10, False, False, False, "X position")
	attr.setDefaultValue(0)
	attr.setValue(-0.24)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",1.71)
else:
	attr = obj.createDoubleAttribute("posY", 1.71, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(1.71)
if obj.getAttribute("posZ") != None :
	obj.setDoubleAttribute("posZ",0)
else:
	attr = obj.createDoubleAttribute("posZ", 0, True, "transform", 30, False, False, False, "Z position")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("rotX") != None :
	obj.setDoubleAttribute("rotX",-30.1697)
else:
	attr = obj.createDoubleAttribute("rotX", -30.1697, True, "transform", 40, False, False, False, "X rotation")
	attr.setDefaultValue(0)
	attr.setValue(-30.1697)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",-19.5491)
else:
	attr = obj.createDoubleAttribute("rotY", -19.5491, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(-19.5491)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",130.109)
else:
	attr = obj.createDoubleAttribute("rotZ", 130.109, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(130.109)
if obj.getAttribute("showCollisionShape") != None :
	obj.setBoolAttribute("showCollisionShape",True)
else:
	attr = obj.createBoolAttribute("showCollisionShape", True, True, "Physics", 370, False, False, False, "Whether the collision shape is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("showStaticMesh") != None :
	obj.setBoolAttribute("showStaticMesh",True)
else:
	attr = obj.createBoolAttribute("showStaticMesh", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)

# ---- light: light1
obj = scene.getPawn("light1")
if obj == None:
	obj = scene.createPawn("light1")
obj.setPosition(SrVec(-0.26, 1.75, 0))
obj.setOrientation(SrQuat(0.698223, -0.630225, 0.0281358, -0.338391))
if obj.getAttribute("blendTexturesWithLighting") != None :
	obj.setBoolAttribute("blendTexturesWithLighting",True)
else:
	attr = obj.createBoolAttribute("blendTexturesWithLighting", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("collisionShape") != None :
	obj.setStringAttribute("collisionShape","null")
else:
	attr = obj.createStringAttribute("collisionShape",  "null", True, "Physics", 350, False, False, False, "Initializes the pawn as a physics object.")
	attr.setDefaultValue("null")
	attr.setValue("null")
	validValues = StringVec()
	validValues.append("null")
	validValues.append("sphere")
	validValues.append("box")
	validValues.append("capsule")
	attr.setValidValues(validValues)
if obj.getAttribute("collisionShapeScale") != None :
	obj.setVec3Attribute("collisionShapeScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("collisionShapeScale",  1, 1, 1, True, "Physics", 360, False, False, False, "Scaling of physics-based shape.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("color") != None :
	obj.setVec3Attribute("color",1, 0, 0)
else:
	attr = obj.createVec3Attribute("color",  1, 0, 0, True, "Display", 6, False, False, False, "Object color.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enablePhysics") != None :
	obj.setBoolAttribute("enablePhysics",False)
else:
	attr = obj.createBoolAttribute("enablePhysics", False, True, "Physics", 310, False, False, False, "Enables or disables physics for this pawn.")
	attr.setDefaultValue(False)
	attr.setValue(False)
if obj.getAttribute("enabled") != None :
	obj.setBoolAttribute("enabled",True)
else:
	attr = obj.createBoolAttribute("enabled", True, True, "LightParameters", 200, False, False, False, "Is the light enabled?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightAmbientColor") != None :
	obj.setVec3Attribute("lightAmbientColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightAmbientColor",  0, 0, 0, True, "LightParameters", 220, False, False, False, " Ambient light color")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("lightCastShadow") != None :
	obj.setBoolAttribute("lightCastShadow",True)
else:
	attr = obj.createBoolAttribute("lightCastShadow", True, True, "LightParameters", 300, False, False, False, "Does the light cast shadow?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightConstantAttenuation") != None :
	obj.setDoubleAttribute("lightConstantAttenuation",1)
else:
	attr = obj.createDoubleAttribute("lightConstantAttenuation", 1, True, "LightParameters", 270, False, False, False, "Constant attenuation")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",1, 0.95, 0.8)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  1, 0.95, 0.8, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 0.95, 0.8)
	attr.setValue(vec1)
if obj.getAttribute("lightIsDirectional") != None :
	obj.setBoolAttribute("lightIsDirectional",True)
else:
	attr = obj.createBoolAttribute("lightIsDirectional", True, True, "LightParameters", 205, False, False, False, "Is the light directional?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightLinearAttenuation") != None :
	obj.setDoubleAttribute("lightLinearAttenuation",1)
else:
	attr = obj.createDoubleAttribute("lightLinearAttenuation", 1, True, "LightParameters", 280, False, False, False, " Linear attenuation.")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("lightQuadraticAttenuation") != None :
	obj.setDoubleAttribute("lightQuadraticAttenuation",0)
else:
	attr = obj.createDoubleAttribute("lightQuadraticAttenuation", 0, True, "LightParameters", 290, False, False, False, "Quadratic attenuation")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("lightShadowMapSize") != None :
	obj.setIntAttribute("lightShadowMapSize",1024)
else:
	attr = obj.createIntAttribute("lightShadowMapSize", 1024, True, "LightParameters", 310, False, False, False, "Size of the shadow map")
	attr.setDefaultValue(1024)
	attr.setValue(1024)
if obj.getAttribute("lightSpecularColor") != None :
	obj.setVec3Attribute("lightSpecularColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightSpecularColor",  0, 0, 0, True, "LightParameters", 230, False, False, False, "Specular light color")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("lightSpotCutoff") != None :
	obj.setDoubleAttribute("lightSpotCutoff",180)
else:
	attr = obj.createDoubleAttribute("lightSpotCutoff", 180, True, "LightParameters", 260, False, False, False, "Spotlight cutoff angle")
	attr.setDefaultValue(180)
	attr.setValue(180)
if obj.getAttribute("lightSpotDirection") != None :
	obj.setVec3Attribute("lightSpotDirection",0, 0, -1)
else:
	attr = obj.createVec3Attribute("lightSpotDirection",  0, 0, -1, True, "LightParameters", 250, False, False, False, "Spotlight direction")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, -1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, -1)
	attr.setValue(vec1)
if obj.getAttribute("lightSpotExponent") != None :
	obj.setDoubleAttribute("lightSpotExponent",0)
else:
	attr = obj.createDoubleAttribute("lightSpotExponent", 0, True, "LightParameters", 240, False, False, False, " Spotlight exponent.")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("mesh") != None :
	obj.setStringAttribute("mesh","")
else:
	attr = obj.createStringAttribute("mesh",  "", True, "Display", 400, False, False, False, "Geometry/mesh")
	attr.setDefaultValue("")
	attr.setValue("")
	validValues = StringVec()
	attr.setValidValues(validValues)
if obj.getAttribute("meshPivot") != None :
	obj.setVec3Attribute("meshPivot",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshPivot",  0, 0, 0, True, "Display", 440, False, False, False, "Mesh pivot offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshRotation") != None :
	obj.setVec3Attribute("meshRotation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshRotation",  0, 0, 0, True, "Display", 430, False, False, False, "Mesh rotation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshScale") != None :
	obj.setVec3Attribute("meshScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("meshScale",  1, 1, 1, True, "Display", 410, False, False, False, "Scale of geometry/mesh")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("meshTranslation") != None :
	obj.setVec3Attribute("meshTranslation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshTranslation",  0, 0, 0, True, "Display", 420, False, False, False, "Mesh translation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("posX") != None :
	obj.setDoubleAttribute("posX",-0.26)
else:
	attr = obj.createDoubleAttribute("posX", -0.26, True, "transform", 10, False, False, False, "X position")
	attr.setDefaultValue(0)
	attr.setValue(-0.26)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",1.75)
else:
	attr = obj.createDoubleAttribute("posY", 1.75, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(1.75)
if obj.getAttribute("posZ") != None :
	obj.setDoubleAttribute("posZ",0)
else:
	attr = obj.createDoubleAttribute("posZ", 0, True, "transform", 30, False, False, False, "Z position")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("rotX") != None :
	obj.setDoubleAttribute("rotX",-59.4329)
else:
	attr = obj.createDoubleAttribute("rotX", -59.4329, True, "transform", 40, False, False, False, "X rotation")
	attr.setDefaultValue(0)
	attr.setValue(-59.4329)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",66.3444)
else:
	attr = obj.createDoubleAttribute("rotY", 66.3444, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(66.3444)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",-92.6357)
else:
	attr = obj.createDoubleAttribute("rotZ", -92.6357, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(-92.6357)
if obj.getAttribute("showCollisionShape") != None :
	obj.setBoolAttribute("showCollisionShape",True)
else:
	attr = obj.createBoolAttribute("showCollisionShape", True, True, "Physics", 370, False, False, False, "Whether the collision shape is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("showStaticMesh") != None :
	obj.setBoolAttribute("showStaticMesh",True)
else:
	attr = obj.createBoolAttribute("showStaticMesh", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)

# ---- light: light2
obj = scene.getPawn("light2")
if obj == None:
	obj = scene.createPawn("light2")
obj.setPosition(SrVec(-0.26, 1.74, 0))
obj.setOrientation(SrQuat(0.678135, 0.70042, -0.214035, -0.0611105))
if obj.getAttribute("blendTexturesWithLighting") != None :
	obj.setBoolAttribute("blendTexturesWithLighting",True)
else:
	attr = obj.createBoolAttribute("blendTexturesWithLighting", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("collisionShape") != None :
	obj.setStringAttribute("collisionShape","null")
else:
	attr = obj.createStringAttribute("collisionShape",  "null", True, "Physics", 350, False, False, False, "Initializes the pawn as a physics object.")
	attr.setDefaultValue("null")
	attr.setValue("null")
	validValues = StringVec()
	validValues.append("null")
	validValues.append("sphere")
	validValues.append("box")
	validValues.append("capsule")
	attr.setValidValues(validValues)
if obj.getAttribute("collisionShapeScale") != None :
	obj.setVec3Attribute("collisionShapeScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("collisionShapeScale",  1, 1, 1, True, "Physics", 360, False, False, False, "Scaling of physics-based shape.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("color") != None :
	obj.setVec3Attribute("color",1, 0, 0)
else:
	attr = obj.createVec3Attribute("color",  1, 0, 0, True, "Display", 6, False, False, False, "Object color.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enablePhysics") != None :
	obj.setBoolAttribute("enablePhysics",False)
else:
	attr = obj.createBoolAttribute("enablePhysics", False, True, "Physics", 310, False, False, False, "Enables or disables physics for this pawn.")
	attr.setDefaultValue(False)
	attr.setValue(False)
if obj.getAttribute("enabled") != None :
	obj.setBoolAttribute("enabled",True)
else:
	attr = obj.createBoolAttribute("enabled", True, True, "LightParameters", 200, False, False, False, "Is the light enabled?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightAmbientColor") != None :
	obj.setVec3Attribute("lightAmbientColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightAmbientColor",  0, 0, 0, True, "LightParameters", 220, False, False, False, " Ambient light color")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("lightCastShadow") != None :
	obj.setBoolAttribute("lightCastShadow",True)
else:
	attr = obj.createBoolAttribute("lightCastShadow", True, True, "LightParameters", 300, False, False, False, "Does the light cast shadow?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightConstantAttenuation") != None :
	obj.setDoubleAttribute("lightConstantAttenuation",1)
else:
	attr = obj.createDoubleAttribute("lightConstantAttenuation", 1, True, "LightParameters", 270, False, False, False, "Constant attenuation")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("lightDiffuseColor") != None :
	obj.setVec3Attribute("lightDiffuseColor",1, 0.95, 0.8)
else:
	attr = obj.createVec3Attribute("lightDiffuseColor",  1, 0.95, 0.8, True, "LightParameters", 210, False, False, False, " Diffuse light color")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 0.95)
	vec.setData(2, 0.8)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 0.95, 0.8)
	attr.setValue(vec1)
if obj.getAttribute("lightIsDirectional") != None :
	obj.setBoolAttribute("lightIsDirectional",True)
else:
	attr = obj.createBoolAttribute("lightIsDirectional", True, True, "LightParameters", 205, False, False, False, "Is the light directional?")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("lightLinearAttenuation") != None :
	obj.setDoubleAttribute("lightLinearAttenuation",1)
else:
	attr = obj.createDoubleAttribute("lightLinearAttenuation", 1, True, "LightParameters", 280, False, False, False, " Linear attenuation.")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("lightQuadraticAttenuation") != None :
	obj.setDoubleAttribute("lightQuadraticAttenuation",0)
else:
	attr = obj.createDoubleAttribute("lightQuadraticAttenuation", 0, True, "LightParameters", 290, False, False, False, "Quadratic attenuation")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("lightShadowMapSize") != None :
	obj.setIntAttribute("lightShadowMapSize",1024)
else:
	attr = obj.createIntAttribute("lightShadowMapSize", 1024, True, "LightParameters", 310, False, False, False, "Size of the shadow map")
	attr.setDefaultValue(1024)
	attr.setValue(1024)
if obj.getAttribute("lightSpecularColor") != None :
	obj.setVec3Attribute("lightSpecularColor",0, 0, 0)
else:
	attr = obj.createVec3Attribute("lightSpecularColor",  0, 0, 0, True, "LightParameters", 230, False, False, False, "Specular light color")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("lightSpotCutoff") != None :
	obj.setDoubleAttribute("lightSpotCutoff",180)
else:
	attr = obj.createDoubleAttribute("lightSpotCutoff", 180, True, "LightParameters", 260, False, False, False, "Spotlight cutoff angle")
	attr.setDefaultValue(180)
	attr.setValue(180)
if obj.getAttribute("lightSpotDirection") != None :
	obj.setVec3Attribute("lightSpotDirection",0, 0, -1)
else:
	attr = obj.createVec3Attribute("lightSpotDirection",  0, 0, -1, True, "LightParameters", 250, False, False, False, "Spotlight direction")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, -1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, -1)
	attr.setValue(vec1)
if obj.getAttribute("lightSpotExponent") != None :
	obj.setDoubleAttribute("lightSpotExponent",0)
else:
	attr = obj.createDoubleAttribute("lightSpotExponent", 0, True, "LightParameters", 240, False, False, False, " Spotlight exponent.")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("mesh") != None :
	obj.setStringAttribute("mesh","")
else:
	attr = obj.createStringAttribute("mesh",  "", True, "Display", 400, False, False, False, "Geometry/mesh")
	attr.setDefaultValue("")
	attr.setValue("")
	validValues = StringVec()
	attr.setValidValues(validValues)
if obj.getAttribute("meshPivot") != None :
	obj.setVec3Attribute("meshPivot",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshPivot",  0, 0, 0, True, "Display", 440, False, False, False, "Mesh pivot offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshRotation") != None :
	obj.setVec3Attribute("meshRotation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshRotation",  0, 0, 0, True, "Display", 430, False, False, False, "Mesh rotation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshScale") != None :
	obj.setVec3Attribute("meshScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("meshScale",  1, 1, 1, True, "Display", 410, False, False, False, "Scale of geometry/mesh")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("meshTranslation") != None :
	obj.setVec3Attribute("meshTranslation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshTranslation",  0, 0, 0, True, "Display", 420, False, False, False, "Mesh translation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("posX") != None :
	obj.setDoubleAttribute("posX",-0.26)
else:
	attr = obj.createDoubleAttribute("posX", -0.26, True, "transform", 10, False, False, False, "X position")
	attr.setDefaultValue(0)
	attr.setValue(-0.26)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",1.74)
else:
	attr = obj.createDoubleAttribute("posY", 1.74, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(1.74)
if obj.getAttribute("posZ") != None :
	obj.setDoubleAttribute("posZ",0)
else:
	attr = obj.createDoubleAttribute("posZ", 0, True, "transform", 30, False, False, False, "Z position")
	attr.setDefaultValue(0)
	attr.setValue(0)
if obj.getAttribute("rotX") != None :
	obj.setDoubleAttribute("rotX",67.4878)
else:
	attr = obj.createDoubleAttribute("rotX", 67.4878, True, "transform", 40, False, False, False, "X rotation")
	attr.setDefaultValue(0)
	attr.setValue(67.4878)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",-100.96)
else:
	attr = obj.createDoubleAttribute("rotY", -100.96, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(-100.96)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",-88.3004)
else:
	attr = obj.createDoubleAttribute("rotZ", -88.3004, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(-88.3004)
if obj.getAttribute("showCollisionShape") != None :
	obj.setBoolAttribute("showCollisionShape",True)
else:
	attr = obj.createBoolAttribute("showCollisionShape", True, True, "Physics", 370, False, False, False, "Whether the collision shape is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("showStaticMesh") != None :
	obj.setBoolAttribute("showStaticMesh",True)
else:
	attr = obj.createBoolAttribute("showStaticMesh", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(False)
