(push (make-pathname :directory (append (pathname-directory *load-truename*)
                                (list "lib" "cl-stomp")))
      asdf:*central-registry*)
(push (make-pathname :directory (append (pathname-directory *load-truename*)
                                (list "lib" "usocket-0.5.5")))
      asdf:*central-registry*)
(push (make-pathname :directory (append (pathname-directory *load-truename*)
                                (list "lib" "babel_0.3.0")))
      asdf:*central-registry*)
(push (make-pathname :directory (append (pathname-directory *load-truename*)
                                (list "lib" "alexandria")))
      asdf:*central-registry*)
(push (make-pathname :directory (append (pathname-directory *load-truename*)
                                (list "lib" "trivial-features_0.6")))
      asdf:*central-registry*)
(push (make-pathname :directory (append (pathname-directory *load-truename*)
                                (list "lib" "threads")))
      asdf:*central-registry*)
(asdf:operate 'asdf:load-op 'vhmsg-lisp)